language: java
os: linux
dist: xenial
jdk:
    - oraclejdk11
addons:
    sonarcloud:
        organization: "kxsystems"
        token: "$SONAR_KEY"
before_install:
    - wget https://github.com/KxSystems/javakdb/archive/refs/tags/1.0.tar.gz
    - tar -xvf 1.0.tar.gz
    - cd javakdb-1.0
    - mvn install
    - cd ..
script:
    - mvn clean verify sonar:sonar -Dsonar.projectKey=KxSystems_jdbc
